### ISSUE TITLE
Sockets implementation

### ISSUE THREAD

**Issue by iHector1** [diogocapela/flatdraw#11]
Hi, I'm have implemented flatdraw in my solution and it's planned to be used as a colaborative whiteboard, and because of that, I need to implemented websockets, so, my question is, how can I manage the functions of flatdraw to do this? I have a barely idea of taking the userMode to redistribute it to the other users but I really don't know if that can work.

Thanks for any help and comment, I really love the project <3.

**Comment by diogocapela** [comment]
It is not an impossible task, but it can be difficult to do properly. If you want multiple users to interact simultaneously with the app and all of them to see the changes in real-time, you would first have to move the canvas objects' state to a centralized server and serve this info from this single websocket server to each React client that connects

**Comment by diogocapela** [comment]
It is not an impossible task, but it can be difficult to do properly. If you want multiple users to interact simultaneously with the app and all of them to see the changes in real-time, you would first have to move the canvas objects' state to a centralized server and serve this info from this single websocket server to each React client that connects
